language: ruby
rvm:
  - 1.9.3
  - ruby-2.0
  - ruby-2.1
  - ruby-head
before_install:
  - source /etc/lsb-release && echo "deb http://download.rethinkdb.com/apt $DISTRIB_CODENAME main" | sudo tee /etc/apt/sources.list.d/rethinkdb.list
  - wget -qO- http://download.rethinkdb.com/apt/pubkey.gpg | sudo apt-key add -
  - sudo apt-get update -q
  - sudo apt-get install rethinkdb
  - sudo cp /etc/rethinkdb/default.conf.sample /etc/rethinkdb/instances.d/instance1.conf
  - sudo service rethinkdb restart
matrix:
  allow_failures:
    - rvm: ruby-head
notifications:
  slack:
    secure: "OAzKYeahS6SoPn1E1OsQFNN8O2sA4/VYbiEapfr/DUNv/kq425ns/J1lBv70mjaRNgoU0rqYNyJ4H5Fo2PAes6mJPjnc1qAXNyWTKHBtSYiVI5kYhE8/3FQbizFx1w/+EZfHu2j3bbeDDBEchJHfYr9wwHf8HlCWIciiZPGS6Ts="
